# -*- coding: utf-8 -*-
import json

# ko: (en, ja, zh-Hans)
T = {
    # 탭 / 공통
    "홈": ("Home", "ホーム", "首页"),
    "기록": ("Records", "記録", "记录"),
    "통계": ("Stats", "統計", "统计"),
    "차고": ("Garage", "ガレージ", "车库"),
    "프로필": ("Profile", "プロフィール", "个人资料"),
    "저장": ("Save", "保存", "保存"),
    "취소": ("Cancel", "キャンセル", "取消"),
    "완료": ("Done", "完了", "完成"),
    "닫기": ("Close", "閉じる", "关闭"),
    "등록": ("Register", "登録", "注册"),
    "예약": ("Book", "予約", "预约"),
    "직접 입력": ("Enter manually", "手動入力", "手动输入"),
    "전체 보기": ("View all", "すべて表示", "查看全部"),
    "사진 선택": ("Choose photo", "写真を選択", "选择照片"),
    "사진 제거": ("Remove photo", "写真を削除", "移除照片"),
    "앨범에서 선택": ("Choose from album", "アルバムから選択", "从相册选择"),

    # 인사
    "안녕하세요": ("Hello", "こんにちは", "您好"),
    "좋은 아침이에요": ("Good morning", "おはようございます", "早上好"),
    "좋은 오후예요": ("Good afternoon", "こんにちは", "下午好"),
    "좋은 저녁이에요": ("Good evening", "こんばんは", "晚上好"),
    "회원님": ("there", "ユーザー", "用户"),
    "어떻게 불러드릴까요?": ("What should we call you?", "何とお呼びしますか？", "怎么称呼您？"),
    "이름": ("Name", "名前", "姓名"),

    # 날씨 / 세차
    "맑음": ("Clear", "快晴", "晴"),
    "대체로 맑음": ("Mostly clear", "おおむね晴れ", "大致晴朗"),
    "흐림": ("Cloudy", "曇り", "阴"),
    "안개": ("Fog", "霧", "雾"),
    "이슬비": ("Drizzle", "霧雨", "毛毛雨"),
    "비": ("Rain", "雨", "雨"),
    "소나기": ("Showers", "にわか雨", "阵雨"),
    "눈": ("Snow", "雪", "雪"),
    "소낙눈": ("Snow showers", "にわか雪", "阵雪"),
    "뇌우": ("Thunderstorm", "雷雨", "雷暴"),
    "세차하기 좋은 날이에요": ("Great day for a car wash", "洗車日和です", "适合洗车的好天气"),
    "비 예보 있음 · 세차는 미루세요": ("Rain expected · hold off on washing", "雨の予報 · 洗車は控えて", "有雨 · 建议暂缓洗车"),
    "비 오는 날 · 세차는 미루세요": ("Rainy day · hold off on washing", "雨の日 · 洗車は控えて", "雨天 · 建议暂缓洗车"),
    "눈길 · 제설제 후 하부 세차 추천": ("Snowy · underbody wash advised after de-icer", "雪道 · 融雪剤後は下回り洗車を", "雪路 · 建议融雪剂后清洗底盘"),
    "안개 · 안전 운전하세요": ("Fog · drive safely", "霧 · 安全運転を", "雾 · 请安全驾驶"),
    "폭염 · 냉각수·타이어 공기압 점검": ("Heat · check coolant & tire pressure", "猛暑 · 冷却水とタイヤ空気圧を点検", "高温 · 检查冷却液和胎压"),
    "한파 · 배터리 방전 주의": ("Cold · watch for battery drain", "寒波 · バッテリー上がりに注意", "寒潮 · 注意电池亏电"),
    "매우 좋음": ("Excellent", "非常に良い", "非常好"),
    "좋음": ("Good", "良い", "好"),
    "보통": ("Fair", "普通", "一般"),
    "나쁨": ("Poor", "悪い", "差"),
    "매우 나쁨": ("Very poor", "非常に悪い", "很差"),
    "안전": ("Safe", "安全", "安全"),
    "과속": ("Over pace", "超過", "超速"),
    "위치 확인 중…": ("Locating…", "位置を確認中…", "正在定位…"),
    "현재 위치": ("Current location", "現在地", "当前位置"),
    "서울": ("Seoul", "ソウル", "首尔"),

    # 홈 대시보드
    "AI 인사이트": ("AI Insights", "AIインサイト", "AI 洞察"),
    "약정거리 예측": ("Mileage forecast", "契約距離の予測", "约定里程预测"),
    "약정거리": ("Contract mileage", "契約距離", "约定里程"),
    "오늘 기준 적정 대비": ("vs. target as of today", "本日時点の適正比", "相对今日基准"),
    "약정 100%": ("Limit 100%", "契約 100%", "约定 100%"),
    "· 여유": ("· margin", "· 余裕", "· 余量"),
    "누적 주행": ("Odometer", "総走行", "总里程"),
    "누적 주행거리": ("Total mileage", "総走行距離", "总行驶里程"),
    "주행 가능 거리": ("Range", "走行可能距離", "可行驶里程"),
    "완충 시 주행": ("Range at full", "満充電時の距離", "满电续航"),
    "현재 배터리": ("Current battery", "現在のバッテリー", "当前电量"),
    "배터리": ("Battery", "バッテリー", "电量"),
    "이번 주 예상 이동": ("Est. travel this week", "今週の予想移動", "本周预计行驶"),
    "예상": ("Est.", "予想", "预计"),
    "절약 플랜 보기": ("View savings plan", "節約プランを見る", "查看省钱方案"),
    "자세히 물어보기": ("Ask more", "詳しく聞く", "了解更多"),
    "이번 달 충전비 얼마 썼어?": ("How much did I spend charging this month?", "今月の充電費はいくら？", "本月充电花了多少？"),
    "최근 기록": ("Recent records", "最近の記録", "最近记录"),
    "아직 기록이 없어요": ("No records yet", "まだ記録がありません", "还没有记录"),
    "이번 주 기록": ("This week's records", "今週の記録", "本周记录"),

    # 길찾기
    "길찾기": ("Directions", "経路案内", "路线导航"),
    "일정": ("Schedule", "予定", "日程"),
    "목적지 검색 (예: 강남역, 서울역)": ("Search destination (e.g. Gangnam Stn.)", "目的地を検索（例: 江南駅）", "搜索目的地（如：江南站）"),
    "어떤 내비로 안내할까요?": ("Which navigation app?", "どのナビで案内しますか？", "使用哪个导航？"),
    "티맵": ("TMAP", "TMAP", "TMAP"),
    "카카오맵": ("KakaoMap", "カカオマップ", "Kakao地图"),

    # 지출/기록 종류
    "충전": ("Charge", "充電", "充电"),
    "주유": ("Fuel", "給油", "加油"),
    "주행": ("Drive", "走行", "行驶"),
    "정비": ("Service", "整備", "保养"),
    "주행 일지": ("Trip log", "走行日誌", "行驶日志"),
    "기타": ("Other", "その他", "其他"),
    "첫 지출 기록": ("First expense record", "最初の支出記録", "首次支出记录"),
    "이번 달 첫 지출 기록": ("First expense this month", "今月最初の支出記録", "本月首次支出"),

    # 기록 추가
    "기록 추가": ("Add record", "記録を追加", "添加记录"),
    "내용": ("Details", "内容", "内容"),
    "금액 (원)": ("Amount (KRW)", "金額（ウォン）", "金额（韩元）"),
    "충전량 (kWh)": ("Energy (kWh)", "充電量（kWh）", "充电量（kWh）"),
    "주유량 (L)": ("Volume (L)", "給油量（L）", "加油量（L）"),
    "거리 (km)": ("Distance (km)", "距離（km）", "距离（km）"),
    "소요 시간 (분)": ("Duration (min)", "所要時間（分）", "用时（分钟）"),
    "예상 정비 항목": ("Suggested service items", "予想整備項目", "预计保养项目"),
    "제목 (아래에서 선택하거나 직접 입력)": ("Title (pick below or type)", "タイトル（下から選択または入力）", "标题（从下方选择或输入）"),
    "제목 (예: 서울 → 판교)": ("Title (e.g. Seoul → Pangyo)", "タイトル（例: ソウル → 板橋）", "标题（如：首尔 → 板桥）"),
    "제목 (예: 초급속 충전 · 42kWh)": ("Title (e.g. Supercharge · 42kWh)", "タイトル（例: 超急速充電 · 42kWh）", "标题（如：超快充 · 42kWh）"),
    "제목 (예: 휘발유 · 40L)": ("Title (e.g. Gasoline · 40L)", "タイトル（例: ガソリン · 40L）", "标题（如：汽油 · 40L）"),
    "장소 (예: 이마트 성수)": ("Place (e.g. E-Mart Seongsu)", "場所（例: イーマート聖水）", "地点（如：易买得城水店）"),
    "정비소 (예: 테슬라 서비스센터)": ("Shop (e.g. Tesla Service Center)", "整備工場（例: テスラサービスセンター）", "维修点（如：特斯拉服务中心）"),
    "주유소 (예: GS칼텍스 역삼)": ("Station (e.g. GS Caltex Yeoksam)", "スタンド（例: GSカルテックス駅三）", "加油站（如：GS加德士驿三）"),
    "태그 (예: 출퇴근)": ("Tag (e.g. Commute)", "タグ（例: 通勤）", "标签（如：通勤）"),

    # 라이딩 지수 (바이크)
    "라이딩": ("Ride", "ライド", "骑行"),
    "노면 결빙·미끄러움 · 라이딩 자제": ("Icy/slippery roads · avoid riding", "路面凍結・スリップ · ライド自粛", "路面结冰湿滑 · 不宜骑行"),
    "우천 노면 · 라이딩 자제": ("Wet roads · avoid riding", "雨天の路面 · ライド自粛", "雨天路面 · 不宜骑行"),
    "안개 · 시야 확보 후 서행": ("Fog · slow down, keep sight lines", "霧 · 視界確保して徐行", "雾 · 确保视野并慢行"),
    "비 예보 · 우비·방수 준비": ("Rain expected · bring rain gear", "雨予報 · レインウェア準備", "有雨 · 备好雨具"),
    "강풍 주의 · 차선 유지 유의": ("Strong wind · mind your lane", "強風注意 · 車線維持に注意", "大风 · 注意保持车道"),
    "저온 · 노면 결빙 주의": ("Cold · watch for icy roads", "低温 · 路面凍結注意", "低温 · 注意路面结冰"),
    "폭염 · 수분 보충·휴식": ("Heat · hydrate and rest", "猛暑 · 水分補給と休憩", "高温 · 补水休息"),
    "라이딩하기 좋은 날이에요": ("Great day for a ride", "ライド日和です", "适合骑行的好天气"),

    # 라이딩/주행 통계
    "이번 달 라이딩": ("This month's rides", "今月のライド", "本月骑行"),
    "이번 달 주행": ("This month's drives", "今月の走行", "本月行驶"),
    "거리": ("Distance", "距離", "距离"),
    "시간": ("Time", "時間", "时长"),
    "%d회": ("%d rides", "%d回", "%d次"),
    "%d시간 %d분": ("%dh %dm", "%d時間%d分", "%d小时%d分"),

    # AI 어시스턴트
    "AI 어시스턴트": ("AI Assistant", "AIアシスタント", "AI 助手"),
    "무엇이든 물어보세요": ("Ask me anything", "何でも聞いてください", "有问必答"),
    "생각 중…": ("Thinking…", "考え中…", "思考中…"),
    "메시지 입력": ("Type a message", "メッセージを入力", "输入消息"),
    "이번 달 지출 분석해줘": ("Analyze this month's spending", "今月の支出を分析して", "分析本月支出"),
    "절약 플랜 알려줘": ("Show me a savings plan", "節約プランを教えて", "给我一个省钱方案"),
    "연비/전비 어때?": ("How's my fuel/energy efficiency?", "燃費/電費はどう？", "油耗/电耗如何？"),
    "다음 정비는 언제야?": ("When's my next service?", "次の整備はいつ？", "下次保养什么时候？"),
    "이번 지출을 분석해서 절약 플랜을 알려줘": ("Analyze my spending and suggest a savings plan", "支出を分析して節約プランを提案して", "分析我的支出并给出省钱方案"),
    "답변을 가져오지 못했어요. 잠시 후 다시 시도해 주세요.": ("Couldn't get an answer. Please try again shortly.", "回答を取得できませんでした。しばらくして再試行してください。", "无法获取回答，请稍后再试。"),
    "듣는 중… 마이크를 다시 누르면 완료": ("Listening… tap mic again to finish", "認識中… マイクを再度押すと完了", "聆听中… 再次点击麦克风结束"),
    "설정에서 마이크·음성 인식 권한을 켜주세요.": ("Enable microphone & speech permissions in Settings.", "設定でマイク・音声認識の権限をオンにしてください。", "请在设置中开启麦克风和语音识别权限。"),
    "대화 기록": ("Chat history", "会話履歴", "对话记录"),
    "저장된 대화가 없어요": ("No saved conversations", "保存された会話がありません", "没有已保存的对话"),
    "대화": ("Conversation", "会話", "对话"),
    "듣기": ("Listen", "聞く", "朗读"),
    "정지": ("Stop", "停止", "停止"),

    # 정비 체크리스트
    "정비 예약 캘린더에 등록": ("Add service appointment to Calendar", "整備予約をカレンダーに登録", "将保养预约添加到日历"),
    "정비 예약": ("Service appointment", "整備予約", "保养预约"),
    "예약 날짜": ("Appointment date", "予約日", "预约日期"),
    "함께 메모될 정비 항목": ("Items noted with it", "メモされる整備項目", "一并备注的项目"),
    "캘린더에 등록": ("Add to Calendar", "カレンダーに登録", "添加到日历"),
    "%@ 정비 예약": ("%@ service appointment", "%@ 整備予約", "%@ 保养预约"),
    "점검 항목:\n": ("Check items:\n", "点検項目:\n", "检查项目:\n"),
    "캘린더에 등록됐어요 (하루 전 알림)": ("Added to Calendar (alert 1 day before)", "カレンダーに登録しました(前日通知)", "已添加到日历(提前一天提醒)"),
    "캘린더 접근이 필요해요": ("Calendar access needed", "カレンダーへのアクセスが必要です", "需要日历访问权限"),
    "정비 체크리스트": ("Service checklist", "整備チェックリスト", "保养清单"),
    "주기 %@km": ("Every %@km", "%@kmごと", "每 %@km"),
    "기록 없음": ("No record", "記録なし", "无记录"),
    "점검 항목 %d개": ("%d items", "点検項目 %d件", "%d 个检查项"),
    "%d건 임박": ("%d due soon", "%d件 間近", "%d 项临近"),
    "정비 기록을 추가하면 그 시점 주행거리를 기준으로 다음 정비 시기를 계산해요. 알림을 켜면 시기가 다가올 때 알려드려요.": ("Add a service record and we'll compute the next due mileage from it. Turn on alerts to be notified as it approaches.", "整備記録を追加すると、その時点の走行距離から次回時期を計算します。通知をオンにすると近づいた時にお知らせします。", "添加保养记录后，将以当时里程计算下次时机。开启提醒后临近时会通知您。"),

    # 계정 / 설정
    "계정": ("Account", "アカウント", "账户"),
    "프리미엄 이용 중": ("Premium member", "プレミアム利用中", "高级会员"),
    "무료 이용 중": ("Free plan", "無料プラン", "免费版"),
    "지원": ("Support", "サポート", "支持"),
    "정보": ("About", "情報", "关于"),
    "앱 평가하기": ("Rate the app", "アプリを評価", "评价应用"),
    "1:1 문의": ("Contact us", "お問い合わせ", "联系我们"),
    "개인정보처리방침": ("Privacy Policy", "プライバシーポリシー", "隐私政策"),
    "이용약관": ("Terms of Service", "利用規約", "服务条款"),
    "버전": ("Version", "バージョン", "版本"),

    # 정비 주기 알림
    "정비 예정": ("Upcoming service", "整備予定", "即将保养"),
    "%dkm 남음": ("%dkm left", "残り %dkm", "剩余 %dkm"),
    "%dkm 초과": ("%dkm overdue", "%dkm 超過", "超出 %dkm"),
    "%@ 정비 시기가 다가와요.": ("%@ service is coming up.", "%@ の整備時期が近づいています。", "%@ 保养时间临近。"),
    "%@ 정비 시기가 지났어요.": ("%@ service is overdue.", "%@ の整備時期が過ぎました。", "%@ 保养已逾期。"),

    # Fleet 역할(기사/관리자)
    "관리자로 시작": ("Start as manager", "管理者として開始", "以管理员开始"),
    "또는": ("or", "または", "或"),
    "기사로 참여": ("Join as driver", "ドライバーとして参加", "以司机身份加入"),
    "참여 코드 (관리자에게 받으세요)": ("Join code (ask your manager)", "参加コード（管理者に確認）", "加入码（向管理员索取）"),
    "참여하기": ("Join", "参加", "加入"),
    "코드를 찾을 수 없어요": ("Code not found", "コードが見つかりません", "找不到该代码"),
    "기사": ("Driver", "ドライバー", "司机"),
    "배정된 차량이 없어요": ("No vehicles assigned", "割り当てられた車両がありません", "没有分配的车辆"),
    "관리자가 차량을 배정하면 여기에 표시돼요": ("Assigned vehicles will appear here", "管理者が車両を割り当てるとここに表示されます", "管理员分配车辆后将显示在此"),
    "참여 코드": ("Join code", "参加コード", "加入码"),
    "기사 %d명": ("%d drivers", "ドライバー %d名", "%d 名司机"),
    "기사 계정 배정": ("Assign driver account", "ドライバーアカウント割当", "分配司机账户"),
    "미배정": ("Unassigned", "未割当", "未分配"),

    # Fleet 인증
    "관리자 계정 만들기": ("Create manager account", "管理者アカウント作成", "创建管理员账户"),
    "관리자 로그인": ("Manager login", "管理者ログイン", "管理员登录"),
    "기업용 Fleet은 계정별로 데이터가 안전하게 분리됩니다.": ("Fleet keeps each account's data securely separated.", "法人フリートはアカウントごとにデータを安全に分離します。", "车队管理按账户安全隔离数据。"),
    "이메일": ("Email", "メール", "邮箱"),
    "비밀번호 (6자 이상)": ("Password (6+ chars)", "パスワード（6文字以上）", "密码（6位以上）"),
    "가입하고 시작": ("Sign up & start", "登録して開始", "注册并开始"),
    "로그인": ("Log in", "ログイン", "登录"),
    "이미 계정이 있어요 · 로그인": ("Have an account · log in", "アカウントをお持ちの方 · ログイン", "已有账户 · 登录"),
    "계정이 없어요 · 가입하기": ("No account · sign up", "アカウントがない · 登録", "没有账户 · 注册"),
    "확인 메일을 보냈어요. 메일 인증 후 로그인해 주세요.": ("Confirmation email sent. Verify then log in.", "確認メールを送信しました。認証後にログインしてください。", "已发送确认邮件，验证后登录。"),
    "인증에 실패했어요.": ("Authentication failed.", "認証に失敗しました。", "认证失败。"),
    "네트워크 오류": ("Network error", "ネットワークエラー", "网络错误"),
    "설정 오류": ("Configuration error", "設定エラー", "配置错误"),
    "로그아웃": ("Log out", "ログアウト", "退出登录"),

    # 기업용 Fleet
    "기업용": ("Business", "法人向け", "企业版"),
    "기업용 Fleet": ("Fleet (Business)", "法人フリート", "车队管理"),
    "택시·운송·렌터카": ("Taxi · transport · rental", "タクシー・運送・レンタカー", "出租·运输·租车"),
    "택시·운송·렌터카 등 다수 차량을 대량 등록하고, 관리자가 한눈에 관리하는 유료 기능이에요.": ("Bulk-register many vehicles and manage them at a glance — a paid feature for taxi, transport and rental fleets.", "多数の車両を一括登録し、管理者が一目で管理できる有料機能です。", "批量登记大量车辆，管理员一目了然管理的付费功能。"),
    "CSV로 차량 대량 등록": ("Bulk-register vehicles via CSV", "CSVで車両を一括登録", "通过CSV批量登记车辆"),
    "관리자 대시보드 · 한눈에 보기": ("Manager dashboard · at a glance", "管理者ダッシュボード · 一目で", "管理员仪表盘 · 一目了然"),
    "차량별 담당 기사 지정": ("Assign a driver per vehicle", "車両ごとに担当ドライバーを指定", "为每辆车指定司机"),
    "Fleet 시작하기": ("Start Fleet", "フリートを始める", "开始车队管理"),
    "조직을 만들어 시작하세요": ("Create an organization to start", "組織を作って始めましょう", "创建组织以开始"),
    "회사/조직 이름 (예: OO운수)": ("Company/org name", "会社・組織名", "公司/组织名称"),
    "조직 만들기": ("Create organization", "組織を作成", "创建组织"),
    "총 %d대": ("%d total", "計%d台", "共 %d 辆"),
    "등록된 차량이 없어요": ("No vehicles registered", "登録された車両がありません", "尚无登记车辆"),
    "CSV 대량등록": ("Bulk import CSV", "CSV一括登録", "CSV批量导入"),
    "CSV 형식: 차량번호,모델,연식,연료,차종,누적주행,기사,연락처": ("CSV: plate,model,year,fuel,type,odometer,driver,phone", "CSV: ナンバー,モデル,年式,燃料,車種,走行,ドライバー,連絡先", "CSV：车牌,型号,年款,燃料,车型,里程,司机,电话"),
    "불러올 차량이 없어요. CSV 형식을 확인하세요.": ("No vehicles found. Check the CSV format.", "読み込む車両がありません。CSV形式を確認してください。", "未找到车辆，请检查CSV格式。"),
    "%d대 대량 등록됨": ("%d vehicles imported", "%d台を一括登録", "已批量登记 %d 辆"),
    "담당 기사": ("Driver", "担当ドライバー", "负责司机"),
    "기사 이름": ("Driver name", "ドライバー名", "司机姓名"),
    "연락처": ("Phone", "連絡先", "联系方式"),
    "차량 삭제": ("Delete vehicle", "車両を削除", "删除车辆"),
    "이 차량을 삭제할까요?": ("Delete this vehicle?", "この車両を削除しますか？", "删除这辆车？"),
    "다음 정비 (km, 선택)": ("Next service (km, optional)", "次回整備 (km, 任意)", "下次保养 (km, 可选)"),
    "전체": ("All", "全体", "全部"),
    "기사별": ("By driver", "ドライバー別", "按司机"),
    "정비 임박": ("Service due", "整備間近", "临近保养"),
    "정비 초과": ("Overdue", "整備超過", "已逾期"),
    "담당 없음": ("Unassigned", "担当なし", "未分配"),
    "내 차량": ("My vehicles", "私の車両", "我的车辆"),
    "주유·주행 기록 추가": ("Add fuel/driving record", "給油・走行記録を追加", "添加加油/行驶记录"),
    "정비 시기를 지난 차량 %d대가 있어요": ("%d vehicle(s) overdue for service", "整備時期を過ぎた車両が%d台あります", "有%d辆车已过保养期"),
    "정비 시기가 임박한 차량 %d대": ("%d vehicle(s) due for service soon", "整備時期が近い車両%d台", "%d辆车临近保养期"),
    "어느 차량 기록을 추가할까요?": ("Which vehicle to add a record for?", "どの車両の記録を追加しますか？", "为哪辆车添加记录？"),
    "해당하는 차량이 없어요": ("No matching vehicles", "該当する車両がありません", "无匹配车辆"),
    "기사 관리": ("Manage drivers", "ドライバー管理", "司机管理"),
    "기사 계정 배정 (교대 시 여러 명 선택)": ("Assign driver accounts (select multiple for shifts)", "ドライバー割当（交代制は複数選択）", "分配司机账户（换班可多选）"),
    "월간 리포트": ("Monthly report", "月次レポート", "月度报告"),
    "이번 달 지출·주행·정비 요약 · PDF 공유": ("This month's spending·driving·service summary · PDF share", "今月の支出・走行・整備の要約・PDF共有", "本月支出·行驶·保养摘要·PDF分享"),
    "PDF로 공유 (카톡·메일)": ("Share as PDF (KakaoTalk·Email)", "PDFで共有（メール等）", "分享为PDF（邮件等）"),
    "%d월 리포트": ("Report for month %d", "%d月レポート", "%d月报告"),
    "%d월 · %@": ("%d월 · %@", "%d月 · %@", "%d月 · %@"),
    "임박한 정비 항목이 없어요": ("No upcoming service items", "近い整備項目はありません", "无临近保养项目"),
    "지난달 대비 %@%d%%": ("%@%d%% vs last month", "先月比 %@%d%%", "较上月 %@%d%%"),
    "담당 %d대": ("%d assigned", "担当%d台", "负责%d辆"),
    "기사별 이번 달 순위": ("Driver ranking this month", "今月のドライバー順位", "本月司机排名"),
    "이번 달 주행": ("This month distance", "今月の走行", "本月行驶"),
    "이번 달 기록": ("This month records", "今月の記録", "本月记录"),
    "이번 달 기록이 없어요": ("No records this month", "今月の記録がありません", "本月无记录"),
    "정비 알림 받기": ("Get service alerts", "整備通知を受け取る", "接收保养提醒"),
    "수동 입력은 무료. 자동화는 프리미엄으로.": ("Manual entry is free. Automation is Premium.", "手動入力は無料。自動化はプレミアムで。", "手动录入免费，自动化需高级版。"),
    "%@ / %@": ("%@ / %@", "%@ / %@", "%@ / %@"),
    "일": ("day", "日", "天"),
    "%d일": ("%d days", "%d日", "%d天"),
    "주": ("week", "週", "周"),
    "월": ("month", "月", "月"),
    "%d개월": ("%d months", "%dか月", "%d个月"),
    "연": ("year", "年", "年"),
    "구독 상품을 불러오는 중이에요.\nApp Store Connect 상품 설정 후 표시됩니다.": ("Loading subscriptions.\nShown after products are set in App Store Connect.", "サブスクを読み込み中です。\nApp Store Connectで商品設定後に表示されます。", "正在加载订阅。\n在App Store Connect设置商品后显示。"),
    "구매 복원": ("Restore", "購入を復元", "恢复购买"),
    "복원할 구매 내역이 없어요.": ("No purchases to restore.", "復元できる購入がありません。", "没有可恢复的购买。"),
    "프로모션 코드": ("Promo code", "プロモコード", "促销码"),
    "구독은 자동 갱신되며, 현재 기간 종료 24시간 전에 취소하지 않으면 동일 금액으로 갱신됩니다. 결제는 App Store 계정으로 청구되며, 설정 > Apple 계정에서 관리·해지할 수 있어요.": ("Subscriptions auto-renew unless canceled at least 24 hours before the current period ends, at the same price. Payment is charged to your App Store account and can be managed or canceled in Settings > Apple Account.", "サブスクは現在の期間終了の24時間前までに解約しない限り同額で自動更新されます。お支払いはApp Storeアカウントに請求され、設定 > Apple アカウントで管理・解約できます。", "订阅将自动续订，除非在当前周期结束前至少24小时取消，续订价格相同。费用将从您的App Store账户扣除，可在设置 > Apple账户中管理或取消。"),
    "영수증·충전 화면 촬영 → AI 자동 입력": ("Snap receipts/charging → AI auto-fill", "レシート・充電画面を撮影 → AI自動入力", "拍摄小票/充电画面 → AI自动录入"),
    "테슬라·타 브랜드 자동 연동 (API·동글)": ("Tesla & other brands auto-sync (API/dongle)", "テスラ・他ブランド自動連携（API・ドングル）", "特斯拉及其他品牌自动同步（API/加密狗）"),
    "슈퍼차저·충전 이력 자동 가져오기": ("Auto-import Supercharger/charging history", "スーパーチャージャー・充電履歴を自動取得", "自动导入超充/充电记录"),
    "차량 여러 대 등록": ("Register multiple vehicles", "車両を複数登録", "登记多辆车"),
    "중고 시세 AI 조회": ("AI used-price lookup", "中古相場AI照会", "二手行情AI查询"),
    "월간 리포트 · PDF 카톡 공유": ("Monthly report · PDF KakaoTalk share", "月次レポート・PDF共有", "月度报告·PDF分享"),
    "테슬라 자동 연동 (프리미엄)": ("Tesla auto-sync (Premium)", "テスラ自動連携（プレミアム）", "特斯拉自动同步（高级版）"),
    "구매": ("Buy", "購入", "购买"),
    "1:1 문의": ("Contact us", "お問い合わせ", "联系我们"),
    "궁금하거나 불편한 점을 남겨주세요. 답변받을 이메일을 함께 적어주시면 회신드려요.": ("Leave your questions or issues. Add your email and we'll reply.", "ご質問やご不便な点をお書きください。メールをご記入いただければ返信します。", "请留下您的问题，附上邮箱我们会回复。"),
    "이메일 (선택)": ("Email (optional)", "メール（任意）", "邮箱（可选）"),
    "회신받을 이메일": ("Email for reply", "返信用メール", "回复邮箱"),
    "문의 내용": ("Message", "お問い合わせ内容", "咨询内容"),
    "보내기": ("Send", "送信", "发送"),
    "문의가 접수됐어요": ("Your inquiry was received", "お問い合わせを受け付けました", "已收到您的咨询"),
    "빠르게 확인하고, 이메일을 남기셨다면 회신드릴게요.": ("We'll review it and reply if you left an email.", "確認し、メールをいただいた場合は返信します。", "我们会查看，若留了邮箱会回复。"),
    "전송 설정이 없어요. 잠시 후 다시 시도해 주세요.": ("Sending is unavailable. Please try again later.", "送信設定がありません。後でもう一度お試しください。", "暂无法发送，请稍后再试。"),
    "전송에 실패했어요. 잠시 후 다시 시도해 주세요.": ("Failed to send. Please try again later.", "送信に失敗しました。後でもう一度お試しください。", "发送失败，请稍后再试。"),
    "관리자": ("Admin", "管理者", "管理员"),
    "문의함": ("Inbox", "受信箱", "收件箱"),
    "처리완료 포함": ("Include handled", "対応済みを含む", "包含已处理"),
    "새로고침": ("Refresh", "更新", "刷新"),
    "처리완료": ("Handled", "対応済み", "已处理"),
    "미처리로": ("Mark unhandled", "未対応に", "标为未处理"),
    "이메일 없음": ("No email", "メールなし", "无邮箱"),
    "새 문의가 없어요": ("No new inquiries", "新しいお問い合わせはありません", "暂无新咨询"),
    "문의가 없어요": ("No inquiries", "お問い合わせはありません", "暂无咨询"),
    "새 문의 %d건이 있어요.": ("You have %d new inquiries.", "新しいお問い合わせが%d件あります。", "有%d条新咨询。"),
    "로그인 계정": ("Signed-in account", "ログイン中のアカウント", "登录账户"),
    "이메일": ("Email", "メール", "邮箱"),
    "로그아웃": ("Sign out", "ログアウト", "退出登录"),
    "계정 삭제": ("Delete account", "アカウント削除", "删除账户"),
    "계정을 삭제할까요?": ("Delete your account?", "アカウントを削除しますか？", "删除您的账户？"),
    "계정과 관련 데이터(조직·차량·기록·배정)가 영구 삭제되며 되돌릴 수 없어요.": ("Your account and related data (organizations, vehicles, records, assignments) will be permanently deleted and cannot be recovered.", "アカウントと関連データ（組織・車両・記録・割当）は完全に削除され、元に戻せません。", "您的账户及相关数据（组织·车辆·记录·分配）将被永久删除且无法恢复。"),
    "계정 삭제에 실패했어요. 잠시 후 다시 시도해 주세요.": ("Failed to delete account. Please try again later.", "アカウント削除に失敗しました。後でもう一度お試しください。", "删除账户失败，请稍后再试。"),
    "개인": ("Personal", "個人", "个人"),
    "업무": ("Work", "業務", "工作"),
    "업무 · %@": ("Work · %@", "業務 · %@", "工作 · %@"),
    "업무 차량": ("Work vehicle", "業務車両", "工作车辆"),
    "첫 차량을 등록하고 시작하세요": ("Register your first vehicle to begin", "最初の車両を登録して始めましょう", "登记您的第一辆车即可开始"),
    "주유·정비·주행 기록과 AI 인사이트를\n내 차량에 맞춰 관리해요.": ("Manage fuel, service, and driving records with AI insights tailored to your vehicle.", "給油・整備・走行の記録とAIインサイトを車両に合わせて管理します。", "按您的车辆管理加油·保养·行驶记录与AI洞察。"),
    "차량 등록하기": ("Register vehicle", "車両を登録", "登记车辆"),
    "테슬라에서 가져오기": ("Import from Tesla", "テスラから取り込む", "从特斯拉导入"),
    "테슬라에서 가져오는 중…": ("Importing from Tesla…", "テスラから取り込み中…", "正在从特斯拉导入…"),
    "테슬라 차량을 가져왔어요": ("Imported your Tesla vehicle", "テスラ車両を取り込みました", "已导入您的特斯拉车辆"),
    "테슬라 차량을 가져오지 못했어요": ("Couldn't import the Tesla vehicle", "テスラ車両を取り込めませんでした", "无法导入特斯拉车辆"),
    "연식": ("Year", "年式", "年份"),
    "선택 안 함": ("Not selected", "選択なし", "未选择"),
    "기록을 추가해 보세요": ("Add a record to begin", "記録を追加してみましょう", "添加一条记录"),
    "기록을 추가하면 맞춤 인사이트를 보여드려요.": ("Add records to see tailored insights.", "記録を追加すると、あなたに合ったインサイトを表示します。", "添加记录后为您显示定制洞察。"),
    "지출 구성": ("Spending breakdown", "支出構成", "支出构成"),
    "추천 용품": ("Recommended parts", "おすすめ用品", "推荐用品"),
    "정비 예정에 맞춰": ("Matched to upcoming service", "整備予定に合わせて", "根据保养计划"),
    "PDF 공유 (카톡·메일)": ("Share PDF (KakaoTalk·Email)", "PDF共有（メール等）", "分享PDF（邮件等）"),
    "엑셀(CSV) 내보내기": ("Export Excel (CSV)", "Excel(CSV)エクスポート", "导出Excel(CSV)"),
    "%d월 · 차량 %d대": ("Month %d · %d vehicles", "%d月 · 車両%d台", "%d月 · %d辆车"),
    "회사": ("Company", "会社", "公司"),
    "소속": ("Organization", "所属", "所属"),
    "다음 정비": ("Next service", "次回整備", "下次保养"),
    "%@ 정비 시기가 지났어요.": ("%@ is overdue for service.", "%@ の整備時期が過ぎました。", "%@ 已过保养期。"),
    "정비가 임박했어요 (%dkm 남음).": ("Service due soon (%dkm left).", "整備が近づいています（残り%dkm）。", "临近保养（剩余%dkm）。"),
    "[%@] %@ 정비 시기가 지났어요.": ("[%@] %@ is overdue for service.", "[%@] %@ の整備時期が過ぎました。", "[%@] %@ 已过保养期。"),
    "[%@] %@ 정비가 임박했어요 (%dkm 남음).": ("[%@] %@ service due soon (%dkm left).", "[%@] %@ の整備が近づいています（残り%dkm）。", "[%@] %@ 临近保养（剩余%dkm）。"),
    "비용": ("Cost", "費用", "费用"),
    "주행": ("Distance", "走行", "行驶"),
    "%d대": ("%d vehicles", "%d台", "%d辆"),
    "이번 달 비용": ("This month's cost", "今月の費用", "本月费用"),
    "기록이 없어요": ("No records", "記録がありません", "无记录"),
    "제목 (예: 경유 40L)": ("Title (e.g. Diesel 40L)", "タイトル（例: 軽油40L）", "标题（如：柴油40L）"),
    "현재 주행 (km, 선택)": ("Current odometer (km, optional)", "現在の走行 (km, 任意)", "当前里程 (km, 可选)"),
    "월간 리포트": ("Monthly report", "月次レポート", "月度报告"),
    "이번 달 합계": ("This month total", "今月の合計", "本月合计"),
    "주유·충전": ("Fuel · charge", "給油・充電", "加油·充电"),
    "총 비용": ("Total cost", "総費用", "总费用"),
    "차량별 이번 달 비용": ("This month's cost by vehicle", "車両別 今月の費用", "各车本月费用"),
    "엑셀 내보내기": ("Export to Excel", "Excelにエクスポート", "导出Excel"),
    "차량": ("Vehicle", "車両", "车辆"),

    # 중고 시세 (프리미엄)
    "중고 시세": ("Resale value", "中古相場", "二手行情"),
    "프리미엄으로 AI 추정 시세 확인": ("Check AI estimate with Premium", "プレミアムでAI推定相場を確認", "高级版查看AI估价"),
    "AI 시세 조회": ("Get AI estimate", "AI相場を取得", "获取AI估价"),
    "시세 추정 중…": ("Estimating…", "推定中…", "估算中…"),
    "조회 중…": ("Loading…", "取得中…", "查询中…"),
    "다시 조회": ("Refresh", "再取得", "重新查询"),
    "최저": ("Low", "最低", "最低"),
    "평균": ("Avg", "平均", "平均"),
    "최고": ("High", "最高", "最高"),
    "AI 추정치 · 실제 시세는 엔카·KB차차차에서 확인": ("AI estimate · verify on used-car sites", "AI推定 · 実際の相場は中古車サイトで確認", "AI估算 · 实际行情请在二手车网站核实"),
    "시세를 추정하지 못했어요. 잠시 후 다시 시도해 주세요.": ("Couldn't estimate. Please try again shortly.", "相場を推定できませんでした。しばらくして再試行してください。", "无法估算，请稍后再试。"),

    # 단골 센터
    "단골 센터": ("My centers", "行きつけの店", "常用中心"),
    "정비소·서비스센터 · 전화·길찾기": ("Shops & centers · call & directions", "整備店・サービス · 電話・経路", "维修点·中心 · 电话·导航"),
    "정비소": ("Repair shop", "整備工場", "维修厂"),
    "카센터": ("Auto center", "カーセンター", "汽车服务"),
    "서비스센터": ("Service center", "サービスセンター", "服务中心"),
    "세차장": ("Car wash", "洗車場", "洗车场"),
    "등록된 센터가 없어요": ("No centers saved yet", "登録された店がありません", "尚无保存的中心"),
    "센터 추가": ("Add center", "店を追加", "添加中心"),
    "센터 수정": ("Edit center", "店を編集", "编辑中心"),
    "센터 삭제": ("Delete center", "店を削除", "删除中心"),
    "이 센터를 삭제할까요?": ("Delete this center?", "この店を削除しますか？", "删除这个中心？"),
    "어떤 지도로 안내할까요?": ("Which map app?", "どの地図アプリ？", "使用哪个地图？"),
    "구글맵": ("Google Maps", "Googleマップ", "谷歌地图"),
    "전화": ("Call", "電話", "电话"),
    "정보": ("Details", "情報", "信息"),
    "이름 (예: 강남 테슬라 서비스센터)": ("Name (e.g. Gangnam Tesla Center)", "名前（例: 江南テスラセンター）", "名称（如：江南特斯拉中心）"),
    "종류": ("Type", "種類", "类型"),
    "주소": ("Address", "住所", "地址"),
    "전화번호": ("Phone", "電話番号", "电话号码"),
    "메모 (선택)": ("Memo (optional)", "メモ（任意）", "备注（可选）"),
    "단골 센터에서 선택": ("Pick from my centers", "行きつけの店から選択", "从常用中心选择"),

    # 차종
    "차종": ("Vehicle type", "車種", "车型"),
    "자동차": ("Car", "自動車", "汽车"),
    "바이크": ("Motorcycle", "バイク", "摩托车"),
    "스쿠터": ("Scooter", "スクーター", "踏板车"),

    # 바이크/스쿠터 정비 항목
    "체인 청소": ("Chain clean", "チェーン清掃", "链条清洁"),
    "체인 급유": ("Chain lube", "チェーン給油", "链条润滑"),
    "체인 조정": ("Chain adjust", "チェーン調整", "链条调整"),
    "체인 교체": ("Chain replace", "チェーン交換", "更换链条"),
    "스프라켓": ("Sprocket", "スプロケット", "链轮"),
    "앞 타이어": ("Front tire", "フロントタイヤ", "前轮胎"),
    "뒤 타이어": ("Rear tire", "リアタイヤ", "后轮胎"),
    "브레이크 오일": ("Brake fluid", "ブレーキオイル", "刹车油"),
    "에어필터": ("Air filter", "エアフィルター", "空气滤清器"),
    "스파크플러그": ("Spark plug", "スパークプラグ", "火花塞"),
    "밸브 간극": ("Valve clearance", "バルブクリアランス", "气门间隙"),
    "냉각수": ("Coolant", "冷却水", "冷却液"),
    "기어오일": ("Gear oil", "ギアオイル", "齿轮油"),
    "구동벨트": ("Drive belt", "駆動ベルト", "传动皮带"),
    "구동롤러": ("Drive roller", "駆動ローラー", "传动滚珠"),

    # 정비 항목
    "엔진오일": ("Engine oil", "エンジンオイル", "机油"),
    "오일필터": ("Oil filter", "オイルフィルター", "机油滤清器"),
    "에어클리너": ("Air cleaner", "エアクリーナー", "空气滤清器"),
    "에어컨 필터": ("A/C filter", "エアコンフィルター", "空调滤清器"),
    "실내필터": ("Cabin filter", "室内フィルター", "空调滤芯"),
    "연료필터": ("Fuel filter", "燃料フィルター", "燃油滤清器"),
    "브레이크 패드": ("Brake pads", "ブレーキパッド", "刹车片"),
    "타이어 공기압": ("Tire pressure", "タイヤ空気圧", "胎压"),
    "타이어 교체": ("Tire replacement", "タイヤ交換", "更换轮胎"),
    "타이어 위치교환": ("Tire rotation", "タイヤローテーション", "轮胎换位"),
    "냉각수 점검": ("Coolant check", "冷却水点検", "冷却液检查"),
    "부동액": ("Antifreeze", "不凍液", "防冻液"),
    "미션오일": ("Transmission oil", "ミッションオイル", "变速箱油"),
    "점화플러그": ("Spark plugs", "点火プラグ", "火花塞"),
    "와이퍼": ("Wipers", "ワイパー", "雨刮器"),
    "하부 세차": ("Underbody wash", "下回り洗車", "底盘清洗"),
    "정기 점검": ("Regular checkup", "定期点検", "定期检查"),
    "엔진오일 교체 알림": ("Engine oil change reminder", "エンジンオイル交換のお知らせ", "机油更换提醒"),

    # 차고 / 차량 정보
    "차량": ("Vehicle", "車両", "车辆"),
    "내 차": ("My car", "マイカー", "我的车"),
    "차량 정보": ("Vehicle info", "車両情報", "车辆信息"),
    "차량 정보 수정": ("Edit vehicle", "車両情報を編集", "编辑车辆信息"),
    "차량 추가": ("Add vehicle", "車両を追加", "添加车辆"),
    "차량 사진": ("Vehicle photo", "車両写真", "车辆照片"),
    "탭해서 차량 사진을 선택하세요": ("Tap to choose a vehicle photo", "タップして車両写真を選択", "点击选择车辆照片"),
    "등록 정보": ("Registration", "登録情報", "登记信息"),
    "종류": ("Type", "種類", "类型"),
    "연료": ("Fuel type", "燃料", "燃料"),
    "모델": ("Model", "モデル", "型号"),
    "제조사": ("Maker", "メーカー", "厂商"),
    "소유 형태": ("Ownership", "所有形態", "拥有方式"),
    "구매": ("Purchase", "購入", "购买"),
    "리스": ("Lease", "リース", "租赁"),
    "렌트": ("Rental", "レンタル", "长租"),
    "구매가": ("Purchase price", "購入価格", "购买价格"),
    "구매가 (원)": ("Purchase price (KRW)", "購入価格（ウォン）", "购买价格（韩元）"),
    "월 납입금": ("Monthly payment", "月額支払い", "月供"),
    "월납입금": ("Monthly payment", "月額支払い", "月供"),
    "월 납입금 (원)": ("Monthly payment (KRW)", "月額支払い（ウォン）", "月供（韩元）"),
    "약정거리 (km)": ("Contract mileage (km)", "契約距離（km）", "约定里程（km）"),
    "렌트 약정거리": ("Rental mileage limit", "レンタル契約距離", "长租约定里程"),
    "계약 시작": ("Contract start", "契約開始", "合同开始"),
    "계약 시작일": ("Contract start date", "契約開始日", "合同开始日"),
    "계약 시작일 설정": ("Set start date", "開始日を設定", "设置开始日期"),
    "계약 시작 시 주행거리 (신차면 0)": ("Odometer at start (0 if new)", "契約開始時の走行距離（新車なら0）", "合同开始时里程（新车填0）"),
    "계약 종료": ("Contract end", "契約終了", "合同结束"),
    "계약 종료일": ("Contract end date", "契約終了日", "合同结束日"),
    "계약 종료일 설정": ("Set end date", "終了日を設定", "设置结束日期"),
    "계약 기간": ("Contract term", "契約期間", "合同期限"),
    "계약일": ("Contract date", "契約日", "合同日期"),
    "약정일": ("Term days", "契約日数", "约定天数"),
    "누적 주행 (km)": ("Odometer (km)", "総走行（km）", "总里程（km）"),
    "누적 주행 km": ("Odometer km", "総走行 km", "总里程 km"),
    "차량 이름 (예: Model Y Long Range)": ("Vehicle name (e.g. Model Y Long Range)", "車両名（例: Model Y Long Range）", "车辆名称（如：Model Y Long Range）"),
    "차량 번호 (예: 62가 3817)": ("Plate (e.g. 62GA 3817)", "ナンバー（例: 62가 3817）", "车牌（如：62가 3817）"),
    "연식 (예: 2024)": ("Year (e.g. 2024)", "年式（例: 2024）", "年款（如：2024）"),

    # 연료 종류
    "전기차": ("EV", "EV", "电动车"),
    "가솔린": ("Gasoline", "ガソリン", "汽油"),
    "디젤": ("Diesel", "ディーゼル", "柴油"),
    "하이브리드": ("Hybrid", "ハイブリッド", "混动"),
    "수소": ("Hydrogen", "水素", "氢能"),

    # 충전소 / 주유소
    "충전소": ("Chargers", "充電スタンド", "充电站"),
    "주변 주유소": ("Nearby stations", "近くのスタンド", "附近加油站"),
    "주변 충전소 찾기": ("Find nearby chargers", "近くの充電器を探す", "查找附近充电站"),
    "주변 검색 중…": ("Searching nearby…", "周辺を検索中…", "正在搜索附近…"),
    "주변 정보를 불러오지 못했어요": ("Couldn't load nearby info", "周辺情報を取得できませんでした", "无法加载附近信息"),
    "오피넷 키 설정 필요": ("Opinet key required", "Opinetキーの設定が必要", "需要设置 Opinet 密钥"),

    # 테슬라
    "테슬라": ("Tesla", "テスラ", "特斯拉"),
    "테슬라 연결": ("Connect Tesla", "テスラを接続", "连接特斯拉"),
    "테슬라 로그인 중…": ("Signing in to Tesla…", "テスラにログイン中…", "正在登录特斯拉…"),
    "테슬라 동기화 (배터리·주행거리)": ("Sync Tesla (battery·odometer)", "テスラ同期（バッテリー·走行距離）", "同步特斯拉（电量·里程）"),
    "슈퍼차저 충전 이력 가져오기": ("Import Supercharger history", "スーパーチャージャー履歴を取得", "导入超充记录"),
    "테슬라 재연결 필요 (충전 이력 권한)": ("Reconnect Tesla (charging permission)", "テスラ再接続が必要（充電履歴の権限）", "需重新连接特斯拉（充电记录权限）"),
    "충전 이력 가져오는 중…": ("Importing charging history…", "充電履歴を取得中…", "正在导入充电记录…"),
    "충전 이력 조회 실패": ("Failed to load charging history", "充電履歴の取得に失敗", "获取充电记录失败"),
    "충전 이력 조회 실패 (%d)": ("Failed to load charging history (%d)", "充電履歴の取得に失敗 (%d)", "获取充电记录失败 (%d)"),
    "테슬라 충전 이력 가져오기": ("Import Tesla charging history", "テスラ充電履歴を取り込む", "导入特斯拉充电记录"),
    "슈퍼차저 충전 내역을 자동 기입": ("Auto-fill Supercharger sessions", "スーパーチャージャー履歴を自動入力", "自动填入超充记录"),
    "테슬라 계정 연결 후 자동 기입": ("Connect Tesla, then auto-fill", "テスラ連携後に自動入力", "连接特斯拉后自动填入"),
    "테슬라 다시 로그인 중…": ("Signing in to Tesla again…", "テスラに再ログイン中…", "正在重新登录特斯拉…"),
    "충전 속도": ("Charging speed", "充電速度", "充电速度"),
    "초고속": ("Ultra-fast", "超急速", "超快充"),
    "고속": ("Fast", "急速", "快充"),
    "완속": ("Slow", "普通", "慢充"),
    "초고속충전": ("Ultra-fast charge", "超急速充電", "超快充"),
    "고속충전": ("Fast charge", "急速充電", "快充"),
    "완속충전": ("Slow charge", "普通充電", "慢充"),
    "충전 이력 권한이 없어요": ("No charging-history permission", "充電履歴の権限がありません", "没有充电记录权限"),
    "테슬라 로그인이 필요해요": ("Tesla sign-in needed", "テスラのログインが必要です", "需要登录特斯拉"),
    "금액이나 내용을 입력해 주세요.": ("Please enter an amount or details.", "金額または内容を入力してください。", "请输入金额或内容。"),
    "요약": ("Summary", "概要", "概要"),
    "월별": ("Monthly", "月別", "按月"),
    "%d년 %d월": ("%d/%d", "%d年%d月", "%d年%d月"),
    "%d회 충전": ("%d sessions", "%d回充電", "%d次充电"),
    "가까운 슈퍼차저": ("Nearby Superchargers", "近くのスーパーチャージャー", "附近的超级充电站"),
    "주변 충전소를 불러오지 못했어요": ("Couldn't load nearby chargers", "周辺の充電所を取得できませんでした", "无法加载附近充电站"),
    "주변 슈퍼차저가 없어요": ("No nearby Superchargers", "近くにスーパーチャージャーがありません", "附近没有超级充电站"),
    "주변 슈퍼차저를 찾는 중…": ("Finding nearby Superchargers…", "近くのスーパーチャージャーを検索中…", "正在查找附近超充…"),
    "차량이 잠자는 중이면 깨우느라 시간이 걸릴 수 있어요.": ("May take a moment if the car is asleep.", "車がスリープ中の場合、時間がかかることがあります。", "车辆休眠时可能需要一些时间。"),
    "차량 현재 위치 기준 · 거리·이용 현황은 실시간이 아닐 수 있어요.": ("Based on the car's location; data may not be live.", "車の現在地基準・距離や空き状況はリアルタイムでない場合があります。", "基于车辆位置；距离和可用情况可能非实时。"),
    "다시 시도": ("Retry", "再試行", "重试"),
    "운영 중지": ("Closed", "停止中", "已停用"),
    "차량 위치": ("Vehicle location", "車両の位置", "车辆位置"),
    "차량 위치 보기": ("View vehicle location", "車両の位置を見る", "查看车辆位置"),
    "차량 위치를 불러오지 못했어요": ("Couldn't load vehicle location", "車両の位置を取得できませんでした", "无法加载车辆位置"),
    "차량 위치를 불러오는 중…": ("Loading vehicle location…", "車両の位置を読み込み中…", "正在加载车辆位置…"),
    "위치 권한이 없어요. 테슬라를 다시 연결해 주세요.": ("No location permission. Reconnect Tesla.", "位置権限がありません。テスラを再接続してください。", "没有位置权限，请重新连接特斯拉。"),
    "테슬라 다시 연결": ("Reconnect Tesla", "テスラを再接続", "重新连接特斯拉"),
    "주행 중": ("Driving", "走行中", "行驶中"),
    "애플 지도": ("Apple Maps", "Appleマップ", "苹果地图"),
    "차량 위치 기준 주변 충전소": ("Chargers near your car", "車の位置周辺の充電所", "车辆附近充电站"),
    "내역 가져오기": ("Import records", "履歴を取り込む", "导入记录"),
    "엑셀·사진으로 여러 건 가져오기": ("Bulk import (Excel/photo)", "Excel・写真で一括取り込み", "批量导入(Excel/照片)"),
    "CSV 파일 또는 내역 사진에서 일괄 등록": ("From a CSV file or a history photo", "CSVファイルまたは履歴写真から一括登録", "从CSV文件或记录照片批量登记"),
    "사진에서 인식": ("From photo", "写真から認識", "从照片识别"),
    "CSV 파일": ("CSV file", "CSVファイル", "CSV文件"),
    "분석 중…": ("Analyzing…", "分析中…", "分析中…"),
    "사진이나 CSV로 여러 건을 한 번에 등록해요.": ("Add many records at once from a photo or CSV.", "写真やCSVで一括登録します。", "通过照片或CSV一次登记多条。"),
    "집·일반 충전기 내역을 채우기 좋아요. (테슬라 슈퍼차저는 자동 임포트)\nCSV 예: 날짜, kWh, 금액, 장소": ("Good for home/other chargers (Tesla Superchargers auto-import).\nCSV: date, kWh, amount, place", "自宅・一般充電器向け(テスラSCは自動)。\nCSV: 日付, kWh, 金額, 場所", "适合家充/其他充电桩(特斯拉超充自动导入)。\nCSV: 日期, kWh, 金额, 地点"),
    "%d건 등록": ("Add %d", "%d件登録", "登记%d条"),
    "인식된 %d건": ("%d found", "%d件認識", "识别%d条"),
    "지우기": ("Clear", "消去", "清除"),
    "인식에 실패했어요. 표가 선명한 사진으로 다시 시도해 주세요.": ("Recognition failed. Try a clearer photo of the table.", "認識に失敗しました。表が鮮明な写真で再試行してください。", "识别失败,请用更清晰的表格照片重试。"),
    "인식된 내역이 없어요.": ("No records found.", "認識された履歴がありません。", "未识别到记录。"),
    "사진에서 %d건 인식했어요. 확인 후 등록하세요.": ("Found %d rows in the photo. Review and add.", "写真から%d件認識。確認して登録してください。", "从照片识别到%d条,请确认后登记。"),
    "파일을 읽지 못했어요": ("Couldn't read the file", "ファイルを読めませんでした", "无法读取文件"),
    "빈 파일이에요": ("The file is empty", "空のファイルです", "文件为空"),
    "인식된 내역이 없어요. 날짜 열을 확인해 주세요.": ("No rows found. Check the date column.", "履歴がありません。日付列を確認してください。", "未识别到记录,请检查日期列。"),
    "CSV에서 %d건 읽었어요. 확인 후 등록하세요.": ("Read %d rows from CSV. Review and add.", "CSVから%d件読み込み。確認して登録してください。", "从CSV读取%d条,请确认后登记。"),
    "%d건 등록됐어요": ("Added %d records", "%d件登録しました", "已登记%d条"),
    "등록 실패: ": ("Failed to add: ", "登録失敗: ", "登记失败: "),
    "가져오기": ("Imported", "取り込み", "导入"),
    "사진 %d/%d 분석 중…": ("Analyzing photo %d/%d…", "写真 %d/%d 分析中…", "分析照片 %d/%d…"),
    "사진 %d장에서 %d건 인식했어요. 확인 후 등록하세요.": ("Found %2$d rows in %1$d photos. Review and add.", "%1$d枚から%2$d件認識。確認して登録してください。", "从%1$d张照片识别到%2$d条,请确认后登记。"),
    "인식된 내역이 없어요. 표가 선명한 사진으로 다시 시도해 주세요.": ("No records found. Try clearer photos.", "履歴がありません。鮮明な写真で再試行してください。", "未识别到记录,请用更清晰的照片重试。"),
    "주변 충전소": ("Nearby chargers", "周辺の充電所", "附近充电站"),
    "%@ 주변 · 지도에서 보기": ("Near %@ · View on map", "%@ 周辺 · 地図で見る", "%@ 附近 · 在地图查看"),
    "주변 충전소를 찾지 못했어요": ("No nearby chargers found", "周辺の充電所が見つかりません", "未找到附近充电站"),
    "주변 충전소를 찾는 중…": ("Finding nearby chargers…", "周辺の充電所を検索中…", "正在查找附近充电站…"),
    "현재 위치 기준 검색 결과 · 실시간 이용 현황은 지도 앱에서 확인하세요.": ("Results near you; check live status in the map app.", "現在地の検索結果・空き状況は地図アプリで確認してください。", "基于当前位置的结果;实时可用情况请在地图应用查看。"),
    "지도에서 보기 · 내비 길찾기": ("View on map · nav directions", "地図で見る · ナビ経路", "在地图查看 · 导航路线"),
    "장소 (주소)": ("Place (address)", "場所(住所)", "地点(地址)"),
    "정비 내역": ("Service details", "整備内容", "保养内容"),
    "예: 테슬라 서비스센터 성수 / 서울 성동구 …": ("e.g., Tesla Service Center · Seoul …", "例: テスラSC · 東京…", "例: 特斯拉服务中心 · …"),
    "예: 타이어 교체, 12개월 점검": ("e.g., Tire change, 12-month check", "例: タイヤ交換, 12ヶ月点検", "例: 更换轮胎, 12个月检查"),
    "시간은 오전 9:00로 등록돼요.": ("Time is set to 9:00 AM.", "時間は午前9:00で登録されます。", "时间将设为上午9:00。"),
    "장소: ": ("Place: ", "場所: ", "地点: "),
    "점검 항목:": ("Check items:", "点検項目:", "检查项目:"),
    "충전 리포트": ("Charging report", "充電レポート", "充电报告"),
    "충전량·지출·장소별 · 휘발유 대비 절약": ("Energy, cost, by place · savings vs gas", "充電量・支出・場所別 · ガソリン比節約", "电量·支出·按地点 · 对比油费节省"),
    "최근 31일": ("Last 31 days", "直近31日", "最近31天"),
    "총 충전량": ("Total energy", "総充電量", "总充电量"),
    "일별 충전량": ("Daily energy", "日別充電量", "每日充电量"),
    "31일 전": ("31 days ago", "31日前", "31天前"),
    "수퍼차저": ("Supercharger", "スーパーチャージャー", "超级充电"),
    "휘발유차 대비 절약": ("Savings vs gas car", "ガソリン車比の節約", "对比燃油车节省"),
    "전기 충전": ("EV charging", "EV充電", "电动充电"),
    "휘발유 등가": ("Gas equivalent", "ガソリン相当", "汽油等价"),
    "추가 주행(추정)": ("Range added (est.)", "追加走行(推定)", "新增里程(估算)"),
    "충전 세션": ("Sessions", "充電セッション", "充电次数"),
    "아직 충전 기록이 없어요": ("No charging records yet", "まだ充電記録がありません", "还没有充电记录"),
    "충전 기록을 추가하거나 테슬라에서 가져오면\n여기에 리포트가 만들어져요.": ("Add a charge or import from Tesla\nto build your report here.", "充電を追加またはテスラから取り込むと\nここにレポートが作成されます。", "添加充电或从特斯拉导入后\n将在此生成报告。"),
    "절약·주행은 추정치예요 (전비 5.0km/kWh · 연비 12km/L · 휘발유 1,700원/L 기준).": ("Savings/range are estimates (5.0km/kWh · 12km/L · ₩1,700/L).", "節約・走行は推定値です (5.0km/kWh · 12km/L · 1,700ウォン/L基準)。", "节省和里程为估算值 (5.0km/kWh · 12km/L · 1,700韩元/L)。"),
    "새 충전 내역 없음": ("No new charging sessions", "新しい充電履歴なし", "没有新的充电记录"),
    "동기화 중…": ("Syncing…", "同期中…", "同步中…"),
    "동기화 완료": ("Synced", "同期完了", "同步完成"),
    "동기화 실패": ("Sync failed", "同期に失敗", "同步失败"),
    "연결됨": ("Connected", "接続済み", "已连接"),
    "연결이 취소되었어요": ("Connection cancelled", "接続がキャンセルされました", "连接已取消"),
    "재연결이 필요해요": ("Reconnection needed", "再接続が必要です", "需要重新连接"),
    "데이터 없음": ("No data", "データなし", "无数据"),
    "차량이 응답하지 않아요 (잠자는 중)": ("Vehicle not responding (asleep)", "車両が応答しません（スリープ中）", "车辆无响应（休眠中）"),
    "인증 URL을 받지 못했어요": ("Couldn't get auth URL", "認証URLを取得できませんでした", "无法获取认证链接"),
    "VIN 확인 실패": ("VIN check failed", "VIN確認に失敗", "VIN 校验失败"),
    "Supabase 미설정": ("Supabase not configured", "Supabase未設定", "未配置 Supabase"),
    "Supabase 미연결 상태 — 저장하려면 연결이 필요해요.": ("Supabase not connected — connection required to save.", "Supabase未接続 — 保存には接続が必要です。", "未连接 Supabase — 保存需要先连接。"),

    # 계약서 PDF
    "계약서 PDF 불러오기": ("Import contract PDF", "契約書PDFを読み込む", "导入合同 PDF"),
    "계약서 분석 중…": ("Analyzing contract…", "契約書を解析中…", "正在分析合同…"),
    "리스·렌트 계약서 PDF에서 계약일·약정일·약정거리를 자동으로 채워요.": ("Auto-fills dates and mileage limit from a lease/rental contract PDF.", "リース・レンタル契約書PDFから契約日・契約日数・契約距離を自動入力します。", "从租赁合同 PDF 自动填写合同日期与约定里程。"),
    "인식된 항목이 없어요. 직접 입력해 주세요.": ("Nothing recognized. Please enter manually.", "認識項目がありません。手動で入力してください。", "未识别到内容，请手动输入。"),

    # 프로필 / Apple
    "Apple 계정에 이름이 없어요. 직접 입력해 주세요.": ("No name on your Apple account. Please enter manually.", "Appleアカウントに名前がありません。手動で入力してください。", "Apple 账户没有姓名，请手动输入。"),
    "Apple 로그인을 사용할 수 없어요. 이름을 직접 입력해 주세요.": ("Sign in with Apple unavailable. Please enter your name.", "Appleでサインインを利用できません。名前を入力してください。", "无法使用 Apple 登录，请手动输入姓名。"),

    # 입력 안내
    "계기판의 현재 누적 주행거리(km)를 입력하세요.": ("Enter the current odometer reading (km).", "メーターの現在の総走行距離（km）を入力してください。", "请输入仪表盘当前总里程（km）。"),
    "현재 배터리 잔량(%)을 입력하세요. 주행 가능 거리가 자동 계산돼요.": ("Enter current battery level (%). Range is calculated automatically.", "現在のバッテリー残量（%）を入力してください。走行可能距離が自動計算されます。", "请输入当前电量（%），可行驶里程将自动计算。"),

    # 샘플 사진
    "샘플 · 레드": ("Sample · Red", "サンプル · レッド", "示例 · 红"),
    "샘플 · 블루": ("Sample · Blue", "サンプル · ブルー", "示例 · 蓝"),
    "샘플 · 스카이": ("Sample · Sky", "サンプル · スカイ", "示例 · 天蓝"),

    # 페이스
    "과속 페이스": ("Over pace", "超過ペース", "超速节奏"),
    "안전 페이스": ("Safe pace", "安全ペース", "安全节奏"),
    "안전": ("Safe", "安全", "安全"),

    # 날짜
    "오늘": ("Today", "今日", "今天"),
    "어제": ("Yesterday", "昨日", "昨天"),

    # 알림
    "오늘의 차량 브리핑을 확인해 보세요.": ("Check today's car briefing.", "今日の車両ブリーフィングを確認しましょう。", "查看今天的车辆简报。"),
    "약정거리 초과 페이스예요. 주행 속도를 조절해 보세요.": ("You're over the mileage pace. Consider driving less.", "契約距離の超過ペースです。走行を調整しましょう。", "已超出约定里程节奏，请适当减少行驶。"),
    "배터리가 부족해요. 충전이 필요해요.": ("Battery is low. Time to charge.", "バッテリーが不足しています。充電が必要です。", "电量不足，需要充电。"),
    "오늘은 세차하기 좋은 날이에요.": ("A great day for a car wash.", "今日は洗車日和です。", "今天适合洗车。"),

    # 스캔 / 프리미엄
    "영수증·충전 화면 스캔": ("Scan receipt / charging screen", "領収書・充電画面をスキャン", "扫描收据/充电界面"),
    "촬영하면 AI가 자동으로 채워요": ("AI fills it in from a photo", "撮影するとAIが自動入力", "拍照后AI自动填写"),
    "프리미엄 · 촬영으로 자동입력": ("Premium · auto-fill from a photo", "プレミアム · 撮影で自動入力", "高级版 · 拍照自动填写"),
    "인식 중…": ("Recognizing…", "認識中…", "识别中…"),
    "스캔할 이미지": ("Image to scan", "スキャンする画像", "要扫描的图片"),
    "카메라로 촬영": ("Take a photo", "カメラで撮影", "拍照"),
    "인식에 실패했어요. 다시 시도하거나 직접 입력해 주세요.": ("Couldn't recognize it. Try again or enter manually.", "認識できませんでした。もう一度試すか手動で入力してください。", "无法识别，请重试或手动输入。"),
    "이미지를 처리할 수 없어요": ("Couldn't process the image", "画像を処理できません", "无法处理图片"),
    "프리미엄": ("Premium", "プレミアム", "高级版"),
    "촬영 한 번으로 기록을 자동으로 채워요.": ("Fill records automatically with a single photo.", "撮影1回で記録を自動入力。", "一张照片自动填写记录。"),
    "영수증·충전 화면 촬영 → AI 자동 입력": ("Photo of receipt/charging → AI auto-fill", "領収書・充電画面の撮影 → AI自動入力", "拍摄收据/充电界面 → AI自动填写"),
    "테슬라 등 차량 자동 연동": ("Auto-sync with Tesla and more", "テスラなど車両の自動連携", "特斯拉等车辆自动同步"),
    "월간 AI 리포트 · 무제한 인사이트": ("Monthly AI report · unlimited insights", "月間AIレポート · 無制限インサイト", "月度AI报告 · 无限洞察"),
    "스마트 알림 · 무제한 기록 보관": ("Smart alerts · unlimited history", "スマート通知 · 無制限の記録保存", "智能提醒 · 无限记录保存"),
    "체험 시작": ("Start trial", "体験を開始", "开始体验"),
    "결제 연동(App Store 구독)은 추후 제공됩니다.": ("App Store subscription billing is coming soon.", "決済連携（App Storeサブスク）は今後提供予定です。", "支付接入（App Store 订阅）即将推出。"),

    # OBD 동글 안내
    "OBD 동글로 자동 연동": ("Auto-sync via OBD dongle", "OBDドングルで自動連携", "通过OBD设备自动同步"),
    "브랜드 무관 · 연료·주행·정비 자동 기록": ("Any brand · auto-log fuel, trips, service", "ブランド不問 · 給油・走行・整備を自動記録", "不限品牌 · 自动记录油耗·行驶·保养"),
    "OBD 동글 연동": ("OBD dongle sync", "OBDドングル連携", "OBD设备同步"),
    "곧 제공돼요": ("Coming soon", "近日提供", "即将推出"),
    "BLE 동글 연결은 준비 중이에요. 지원 동글을 미리 준비해두시면 출시되는 대로 바로 쓸 수 있어요.": ("BLE dongle connection is in the works. Get a supported dongle ready so you can use it as soon as it launches.", "BLEドングル接続は準備中です。対応ドングルを用意しておくと公開後すぐ使えます。", "BLE设备连接正在开发中。备好支持的设备，上线即可使用。"),
    "브랜드 상관없이 자동 기록": ("Auto-log, any brand", "ブランド不問で自動記録", "任意品牌自动记录"),
    "OBD 동글 하나면 연료·주행거리·정비코드를 자동으로": ("One OBD dongle auto-captures fuel, mileage, and trouble codes", "OBDドングル1つで給油・走行距離・故障コードを自動取得", "一个OBD设备自动采集油耗、里程和故障码"),
    "이렇게 동작해요": ("How it works", "使い方", "工作原理"),
    "동글을 OBD 단자에 꽂기": ("Plug the dongle into the OBD port", "ドングルをOBD端子に挿す", "将设备插入OBD接口"),
    "운전석 아래 진단 단자에 연결 (2005년 이후 차량 대부분)": ("Connect to the port under the dash (most cars after 2005)", "運転席下の診断端子に接続（2005年以降の多くの車）", "连接方向盘下方的诊断口（2005年后多数车型）"),
    "블루투스로 연결": ("Connect via Bluetooth", "Bluetoothで接続", "通过蓝牙连接"),
    "앱이 BLE 동글을 찾아 자동 연결": ("The app finds and connects the BLE dongle", "アプリがBLEドングルを見つけて自動接続", "应用自动查找并连接BLE设备"),
    "시동 시 자동 기록": ("Auto-log when you drive", "始動時に自動記録", "启动时自动记录"),
    "주유·주행·정비 데이터가 자동으로 차계부에 반영": ("Fuel, trip, and service data flow into your log automatically", "給油・走行・整備データが自動で記録に反映", "油耗·行驶·保养数据自动记入账本"),
    "무엇이 채워지나요": ("What gets filled in", "何が入力される？", "会填入哪些内容"),
    "연료 잔량": ("Fuel level", "燃料残量", "油量"),
    "주행거리": ("Mileage", "走行距離", "里程"),
    "VIN 자동인식": ("Auto VIN", "VIN自動認識", "自动识别VIN"),
    "정비 경고(DTC)": ("Service alerts (DTC)", "整備警告(DTC)", "保养警告(DTC)"),
    "주행 트립": ("Trip distance", "走行トリップ", "行程"),
    "iPhone은 BLE(저전력 블루투스) 동글만 지원해요. 저가 ‘블루투스 클래식’ ELM327은 iOS에서 동작하지 않으니 아래 목록에서 고르세요.": ("iPhone supports only BLE (low-energy Bluetooth) dongles. Cheap ‘Bluetooth Classic’ ELM327 units don't work on iOS — pick from the list below.", "iPhoneはBLE（低消費電力Bluetooth）ドングルのみ対応。安価な『Bluetoothクラシック』ELM327はiOSで動作しないため、下記から選んでください。", "iPhone仅支持BLE（低功耗蓝牙）设备。廉价的‘经典蓝牙’ELM327在iOS上无法使用，请从下方选择。"),
    "iOS 호환 추천 동글": ("Recommended iOS-compatible dongles", "iOS対応おすすめドングル", "iOS兼容推荐设备"),
    "추천": ("Top pick", "おすすめ", "推荐"),
    "가성비": ("Value", "コスパ", "高性价比"),
    "전기차 배터리 잔량은 표준 OBD로 안 나와요. 전기차는 테슬라 연동이 더 정확하고, 동글은 내연기관차에 강력해요.": ("EV battery level isn't exposed via standard OBD. For EVs, Tesla sync is more accurate; dongles shine for gas cars.", "EVのバッテリー残量は標準OBDでは取得できません。EVはテスラ連携が正確で、ドングルはガソリン車に強力です。", "标准OBD无法读取电动车电量。电动车用特斯拉同步更准确，OBD设备更适合燃油车。"),
    "동글 연결 준비하기": ("Get ready to connect", "接続の準備をする", "准备连接"),
    "프리미엄으로 동글 연동": ("Dongle sync with Premium", "プレミアムでドングル連携", "高级版设备同步"),
    "동글 연결하기": ("Connect dongle", "ドングルを接続", "连接设备"),
    "BLE(저전력 블루투스) 동글이 필요해요.": ("A BLE (low-energy Bluetooth) dongle is required.", "BLE（低消費電力Bluetooth）ドングルが必要です。", "需要BLE（低功耗蓝牙）设备。"),

    # OBD 연결 화면
    "OBD 동글 연결": ("Connect OBD dongle", "OBDドングル接続", "连接OBD设备"),
    "동글을 꽂고 시동을 켠 뒤 스캔하세요": ("Plug in the dongle, start the car, then scan", "ドングルを挿し、エンジンをかけてスキャン", "插入设备并启动车辆后扫描"),
    "동글 검색": ("Search dongles", "ドングルを検索", "搜索设备"),
    "주변 동글 검색 중…": ("Searching nearby dongles…", "周辺のドングルを検索中…", "正在搜索附近设备…"),
    "BLE 동글이 보이지 않으면, 동글이 켜져 있고 iOS 호환(BLE)인지 확인하세요.": ("If no BLE dongle appears, check it's powered and iOS-compatible (BLE).", "BLEドングルが表示されない場合、電源とiOS対応(BLE)を確認してください。", "若未显示BLE设备，请确认其已通电且兼容iOS(BLE)。"),
    "동글 초기화 중…": ("Initializing dongle…", "ドングルを初期化中…", "正在初始化设备…"),
    "차량 데이터 읽는 중…": ("Reading vehicle data…", "車両データを読み取り中…", "正在读取车辆数据…"),
    "연결 중…": ("Connecting…", "接続中…", "连接中…"),
    "서비스 탐색 중…": ("Discovering services…", "サービスを探索中…", "正在发现服务…"),
    "연결에 실패했어요": ("Connection failed", "接続に失敗しました", "连接失败"),
    "이 차량은 표준 OBD 값을 제공하지 않아요.": ("This vehicle doesn't expose standard OBD values.", "この車両は標準OBD値を提供しません。", "该车辆不提供标准OBD数据。"),
    "읽기 완료": ("Read complete", "読み取り完了", "读取完成"),
    "블루투스를 켜주세요.": ("Please turn on Bluetooth.", "Bluetoothをオンにしてください。", "请打开蓝牙。"),
    "주행 트립": ("Trip distance", "走行トリップ", "行程"),
    "누적 주행을 차량에 반영": ("Apply odometer to vehicle", "総走行を車両に反映", "将里程写入车辆"),
    "반영됨": ("Applied", "反映済み", "已写入"),
    "다시 검색": ("Search again", "再検索", "重新搜索"),

    # 통계 브리핑 폴백
    "이번 달 지출 %@": ("This month's spend %@", "今月の支出 %@", "本月支出 %@"),
    "적정 대비 %d%%": ("%d%% of target pace", "適正比 %d%%", "相对适宜 %d%%"),
    "기록 %d건": ("%d records", "記録 %d件", "%d条记录"),
    "기록을 추가하면 맞춤 브리핑을 보여드려요.": ("Add records to get a personalized briefing.", "記録を追加すると専用ブリーフィングを表示します。", "添加记录后即可查看个性化简报。"),

    # 기록 수정 / 상태
    "기록 수정": ("Edit record", "記録を編集", "编辑记录"),
    "기록 삭제": ("Delete record", "記録を削除", "删除记录"),
    "이 기록을 삭제할까요?": ("Delete this record?", "この記録を削除しますか？", "删除这条记录？"),
    "운행 중": ("Driving", "走行中", "行驶中"),
    "충전 중": ("Charging", "充電中", "充电中"),

    # 언어
    "언어": ("Language", "言語", "语言"),
    "시스템 기본값": ("System default", "システム既定", "系统默认"),
    "언어 변경": ("Language changed", "言語の変更", "语言更改"),
    "언어를 변경했어요. 앱을 완전히 종료 후 다시 실행하면 적용됩니다.": ("Language changed. Fully quit and relaunch the app to apply.", "言語を変更しました。アプリを完全に終了して再起動すると適用されます。", "已更改语言。完全退出并重新启动应用后生效。"),
    "확인": ("OK", "OK", "确定"),

    # 포맷 문자열 (%d/%@ 등 위치자 유지)
    "충전 %d건 가져옴": ("Imported %d charges", "%d件の充電を取得", "已导入 %d 条充电"),
    "오늘 강수 %d%% · 내일 %d%%": ("Rain today %d%% · tomorrow %d%%", "本日の降水 %d%% · 明日 %d%%", "今日降水 %d%% · 明日 %d%%"),
    "세차": ("Wash", "洗車", "洗车"),
    "배터리 %d%%": ("Battery %d%%", "バッテリー %d%%", "电量 %d%%"),
    "%d월 지출": ("Spend · mo. %d", "%d月の支出", "%d月支出"),
    "%d월 총 지출": ("Total · mo. %d", "%d月の合計支出", "%d月总支出"),
    "· %d%% 빠름": ("· %d%% fast", "· %d%% 速い", "· 快 %d%%"),
    "오늘 적정 %@km · 현재 %@km": ("Target %@km · now %@km", "適正 %@km · 現在 %@km", "适宜 %@km · 当前 %@km"),
    "하루 %d/%dkm": ("%d/%d km per day", "1日 %d/%dkm", "每天 %d/%dkm"),
    "만료 시 예상 %@km / 약정 %@km": ("Est. %@km / limit %@km", "満了時 %@km / 契約 %@km", "到期预计 %@km / 约定 %@km"),
    "%d분": ("%d min", "%d分", "%d分钟"),
    " · %d분": (" · %d min", " · %d分", " · %d分钟"),
    "지난달보다 %@ 아꼈어요": ("Saved %@ vs last month", "先月より %@ 節約", "比上月省 %@"),
    "지난달보다 %@ 더 썼어요": ("Spent %@ more vs last month", "先月より %@ 増加", "比上月多花 %@"),
    "잔여 %@km": ("%@km left", "残り %@km", "剩余 %@km"),
    "%@km 주행": ("%@km driven", "%@km 走行", "已行驶 %@km"),
    "약정 %@km": ("Limit %@km", "契約 %@km", "约定 %@km"),
    "최저 %@ · %@": ("Lowest %@ · %@", "最安 %@ · %@", "最低 %@ · %@"),
    "%@ 주변 · 카카오맵에서 보기": ("Near %@ · view on KakaoMap", "%@ 周辺 · カカオマップで見る", "%@ 附近 · Kakao地图查看"),
    "평균 %@": ("Avg %@", "平均 %@", "均价 %@"),
    "전국 평균 (%@)": ("National avg (%@)", "全国平均 (%@)", "全国均价 (%@)"),
}

# 코드에는 있으나 목업/데모 데이터 → 그대로 두면 한글 노출되므로 최소 번역
MOCK = {
    "62가 3817": ("62GA 3817", "62가 3817", "62가 3817"),
    "강남 미팅": ("Gangnam meeting", "江南ミーティング", "江南会议"),
    "강남역": ("Gangnam Stn.", "江南駅", "江南站"),
    "판교역": ("Pangyo Stn.", "板橋駅", "板桥站"),
    "판교 방문": ("Pangyo visit", "板橋訪問", "板桥拜访"),
    "이마트 성수": ("E-Mart Seongsu", "イーマート聖水", "易买得城水"),
    "출퇴근": ("Commute", "通勤", "通勤"),
    "세컨카": ("Second car", "セカンドカー", "第二辆车"),
    "주차 중": ("Parked", "駐車中", "停车中"),
    "충전량 (kWh)": ("Energy (kWh)", "充電量（kWh）", "充电量（kWh）"),
}
T.update(MOCK)

strings = {}
for ko, (en, ja, zh) in T.items():
    strings[ko] = {
        "localizations": {
            "en": {"stringUnit": {"state": "translated", "value": en}},
            "ja": {"stringUnit": {"state": "translated", "value": ja}},
            "zh-Hans": {"stringUnit": {"state": "translated", "value": zh}},
        }
    }

catalog = {"sourceLanguage": "ko", "strings": strings, "version": "1.0"}
out = "/Users/kimchannyeon/Documents/Claude/vault/ios/Vault/Localizable.xcstrings"
with open(out, "w", encoding="utf-8") as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)
    f.write("\n")
print("keys:", len(strings))
